import type { NewCategory } from '@/database/schema';

export const DEFAULT_CATEGORIES: NewCategory[] = [
  {
    id: 'inc-salary',
    name: 'Salary',
    nameTh: 'เงินเดือน',
    type: 'income',
    icon: 'cash',
    color: '#10B981',
    defaultSection40: 1,
    isSystem: true,
    displayOrder: 1,
    isActive: true,
  },
  {
    id: 'inc-freelance',
    name: 'Freelance',
    nameTh: 'ฟรีแลนซ์',
    type: 'income',
    icon: 'laptop',
    color: '#3B82F6',
    defaultSection40: 2,
    isSystem: true,
    displayOrder: 2,
    isActive: true,
  },
  {
    id: 'inc-intellectual',
    name: 'Royalties',
    nameTh: 'ค่าลิขสิทธิ์',
    type: 'income',
    icon: 'book-open',
    color: '#8B5CF6',
    defaultSection40: 3,
    isSystem: true,
    displayOrder: 3,
    isActive: true,
  },
  {
    id: 'inc-dividend',
    name: 'Dividend & Interest',
    nameTh: 'เงินปันผลและดอกเบี้ย',
    type: 'income',
    icon: 'trending-up',
    color: '#F59E0B',
    defaultSection40: 4,
    isSystem: true,
    displayOrder: 4,
    isActive: true,
  },
  {
    id: 'inc-rental',
    name: 'Rental Income',
    nameTh: 'ค่าเช่าทรัพย์สิน',
    type: 'income',
    icon: 'home',
    color: '#EC4899',
    defaultSection40: 5,
    isSystem: true,
    displayOrder: 5,
    isActive: true,
  },
  {
    id: 'inc-professional',
    name: 'Professional Services',
    nameTh: 'วิชาชีพอิสระ',
    type: 'income',
    icon: 'briefcase',
    color: '#06B6D4',
    defaultSection40: 6,
    isSystem: true,
    displayOrder: 6,
    isActive: true,
  },
  {
    id: 'inc-contract',
    name: 'Contract Work',
    nameTh: 'การรับเหมา',
    type: 'income',
    icon: 'file-sign',
    color: '#F97316',
    defaultSection40: 7,
    isSystem: true,
    displayOrder: 7,
    isActive: true,
  },
  {
    id: 'inc-business',
    name: 'Business Income',
    nameTh: 'ธุรกิจ',
    type: 'income',
    icon: 'store',
    color: '#84CC16',
    defaultSection40: 8,
    isSystem: true,
    displayOrder: 8,
    isActive: true,
  },
  {
    id: 'inc-other',
    name: 'Other Income',
    nameTh: 'รายได้อื่น',
    type: 'income',
    icon: 'plus-circle',
    color: '#6366F1',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 9,
    isActive: true,
  },
  {
    id: 'exp-food',
    name: 'Food & Dining',
    nameTh: 'อาหารและเครื่องดื่ม',
    type: 'expense',
    icon: 'food',
    color: '#EF4444',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 10,
    isActive: true,
  },
  {
    id: 'exp-transport',
    name: 'Transportation',
    nameTh: 'ค่าเดินทาง',
    type: 'expense',
    icon: 'car',
    color: '#F97316',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 11,
    isActive: true,
  },
  {
    id: 'exp-utilities',
    name: 'Utilities',
    nameTh: 'ค่าสาธารณูปโภค',
    type: 'expense',
    icon: 'flash',
    color: '#EAB308',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 12,
    isActive: true,
  },
  {
    id: 'exp-shopping',
    name: 'Shopping',
    nameTh: 'ช็อปปิ้ง',
    type: 'expense',
    icon: 'shopping',
    color: '#8B5CF6',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 13,
    isActive: true,
  },
  {
    id: 'exp-healthcare',
    name: 'Healthcare',
    nameTh: 'สุขภาพ',
    type: 'expense',
    icon: 'medical-bag',
    color: '#06B6D4',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 14,
    isActive: true,
  },
  {
    id: 'exp-entertainment',
    name: 'Entertainment',
    nameTh: 'บันเทิง',
    type: 'expense',
    icon: 'movie',
    color: '#EC4899',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 15,
    isActive: true,
  },
  {
    id: 'exp-education',
    name: 'Education',
    nameTh: 'การศึกษา',
    type: 'expense',
    icon: 'school',
    color: '#14B8A6',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 16,
    isActive: true,
  },
  {
    id: 'exp-insurance',
    name: 'Insurance',
    nameTh: 'ประกันภัย',
    type: 'expense',
    icon: 'shield-check',
    color: '#64748B',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 17,
    isActive: true,
  },
  {
    id: 'exp-housing',
    name: 'Housing',
    nameTh: 'ที่อยู่อาศัย',
    type: 'expense',
    icon: 'home-variant',
    color: '#7C2D12',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 18,
    isActive: true,
  },
  {
    id: 'exp-investment',
    name: 'Investment',
    nameTh: 'การลงทุน',
    type: 'expense',
    icon: 'chart-line',
    color: '#15803D',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 19,
    isActive: true,
  },
  {
    id: 'exp-other',
    name: 'Other Expenses',
    nameTh: 'รายจ่ายอื่น',
    type: 'expense',
    icon: 'dots-horizontal',
    color: '#6B7280',
    defaultSection40: null,
    isSystem: true,
    displayOrder: 20,
    isActive: true,
  },
];

export const CATEGORY_ICONS: Record<string, string> = {
  'cash': 'cash',
  'laptop': 'laptop',
  'book-open': 'book-open-variant',
  'trending-up': 'trending-up',
  'home': 'home',
  'briefcase': 'briefcase',
  'file-sign': 'file-document',
  'store': 'store',
  'plus-circle': 'plus-circle',
  'food': 'food',
  'car': 'car',
  'flash': 'flash',
  'shopping': 'shopping',
  'medical-bag': 'medical-bag',
  'movie': 'movie',
  'school': 'school',
  'shield-check': 'shield-check',
  'home-variant': 'home-variant',
  'chart-line': 'chart-line',
  'dots-horizontal': 'dots-horizontal',
};
